# 📄 health_check.py
# This script focuses on the "Teleportation Target." It verifies that a process we captured actually exists and is still running properly after a restoration.

"""
WekezaOmniOS Process Health Check
Verifies the status of specific teleported processes.
"""

import psutil
import os

def check_process_alive(pid):
    """Checks if a specific PID is active and responding."""
    try:
        process = psutil.Process(pid)
        return process.is_running() and process.status() != psutil.STATUS_ZOMBIE
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return False

def verify_teleportation_sync(pid_file_path):
    """Reads a PID from the temp folder and verifies health."""
    if not os.path.exists(pid_file_path):
        print(f"[Health Check] Error: PID file {pid_file_path} not found.")
        return False

    with open(pid_file_path, "r") as f:
        try:
            pid = int(f.read().strip())
            is_alive = check_process_alive(pid)
            print(f"[Health Check] Process {pid} Status: {'ACTIVE' if is_alive else 'DEAD/MISSING'}")
            return is_alive
        except ValueError:
            print("[Health Check] Error: Invalid PID format in file.")
            return False

if __name__ == "__main__":
    # Test against the demo app PID generated by scripts/run_demo.sh
    verify_teleportation_sync("temp/demo_app.pid")
